#!/usr/bin/env python3
"""Build a reproducible synthetic package; no business URLs, accounts, or assets."""
from pathlib import Path
import hashlib
import zipfile
root = Path(__file__).resolve().parents[1]
archive = root / 'Demo/Resources/demo.zip'
archive.parent.mkdir(parents=True, exist_ok=True)
with zipfile.ZipFile(archive, 'w') as output:
    for path in sorted((root / 'Demo/Web').iterdir()):
        info = zipfile.ZipInfo(path.name, (2024, 1, 1, 0, 0, 0))
        info.compress_type = zipfile.ZIP_DEFLATED
        info.external_attr = 0o100644 << 16
        output.writestr(info, path.read_bytes())
digest = hashlib.sha256(archive.read_bytes()).hexdigest()
(root / 'Demo/PackageDigest.h').write_text('// Generated by scripts/generate_demo.py\n#define OFT_DEMO_SHA256 @"' + digest + '"\n')
print(digest)
